global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'air-purifier-server'
    static_configs:
      - targets: ['dummy_server:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'